services:
  api:
    build:
      context: .
      target: development
    environment:
      CITY_API_ADDR: "${CITY_API_ADDR}"
      CITY_API_PORT: "${CITY_API_PORT}"
      CITY_API_DB_USER: "${CITY_API_DB_USER}"
      CITY_API_DB_PWD: "${CITY_API_DB_PWD}"
      CITY_API_DB_URL: "${CITY_API_DB_URL}"
      DATABASE_URL: "${CITY_API_DB_URL}"
    depends_on:
      - db
    networks:
      - api-tier
    ports:
      - "${HOST_API_ADDR:-127.0.0.1}:${HOST_API_PORT:-2022}:${CITY_API_PORT:-2022}"
    volumes:
      - ./src/:/usr/app/src
      - ./sql/:/usr/app/sql
      - ./Cargo.toml:/usr/app/Cargo.toml
      - ./Cargo.lock:/usr/app/Cargo.lock
      - cargo-target:/usr/app/target
      - cargo-bin:/usr/local/cargo

  db:
    image: bitnami/postgresql:12.14.0
    restart: always
    environment:
      POSTGRESQL_USERNAME: "${CITY_API_DB_USER}"
      POSTGRESQL_PASSWORD: "${CITY_API_DB_PWD}"
      POSTGRESQL_DATABASE: "${CITY_API_DB_NAME:-city-db}"
    networks:
      - api-tier
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/bitnami/postgresql
      - ./sql/:/docker-entrypoint-initdb.d/

networks:
  api-tier:
volumes:
  cargo-target:
  cargo-bin:
  db-data: