services:
  api:
    image: ghcr.io/lapsus-ord/city-api:latest
    # build:
    #   context: .
    #   target: production
    environment:
      CITY_API_ADDR: "${CITY_API_ADDR}"
      CITY_API_PORT: "${CITY_API_PORT}"
      CITY_API_DB_USER: "${CITY_API_DB_USER}"
      CITY_API_DB_PWD: "${CITY_API_DB_PWD}"
      CITY_API_DB_URL: "${CITY_API_DB_URL}"
      RUST_BACKTRACE: 1
    depends_on:
      - db
    networks:
      - api-tier
      - metrics-tier
    ports:
      - "127.0.0.1:${HOST_API_PORT}:${CITY_API_PORT:-80}"

  db:
    image: bitnami/postgresql:12.14.0
    environment:
      POSTGRESQL_USERNAME: "${CITY_API_DB_USER}"
      POSTGRESQL_PASSWORD: "${CITY_API_DB_PWD}"
      POSTGRESQL_DATABASE: "${CITY_API_DB_NAME:-city-db}"
    networks:
      - api-tier
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db-data:/bitnami/postgresql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  prometheus:
    image: bitnami/prometheus:2.45.0
    ports:
      - 3010:9090
    volumes:
      - ./metrics/prometheus/prometheus.yaml:/opt/bitnami/prometheus/conf/prometheus.yml
    networks:
      - metrics-tier

  grafana:
    image: bitnami/grafana:9.5.5
    ports:
      - 3005:3000
    volumes:
      - ./metrics/grafana:/opt/bitnami/grafana/conf/provisioning
    networks:
      - metrics-tier

networks:
  api-tier:
  metrics-tier:

volumes:
  db-data:
