name: Build Docker image

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push to GHCR
        run: |
          docker build . --tag ghcr.io/lapsus-ord/city-api:latest --target production
          docker push ghcr.io/lapsus-ord/city-api:latest
