name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings

  test:
      name: Test
      runs-on: ubuntu-latest
      env:
        CITY_API_DB_USER: city-api
        CITY_API_DB_PWD: CHANGEME
        CITY_API_DB_URL: postgresql://city-api:CHANGEME@db:5432/city-db?schema=public
      services:
        db:
          image: bitnami/postgresql:12.14.0
          env:
            POSTGRESQL_USERNAME: city-api
            POSTGRESQL_PASSWORD: CHANGEME
            POSTGRESQL_DATABASE: city-db
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - name: Run tests
          run: cargo test
