name: CI

on: [push, pull_request]

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true

jobs:
  fmt:
    name: Rustfmt
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt
      - name: Enforce formatting
        run: cargo fmt --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy
      - uses: Swatinem/rust-cache@v2
      - name: Linting
        run: cargo clippy -- -D warnings

  test:
      name: Test
      runs-on: ubuntu-latest
      env:
        CITY_API_DB_USER: root
        CITY_API_DB_PWD: root
        CITY_API_DB_URL: postgresql://root:root@postgres:5432/city-db?schema=public
      services:
        postgres:
          image: bitnami/postgresql:12.14.0
          env:
            POSTGRESQL_USERNAME: root
            POSTGRESQL_PASSWORD: root
            POSTGRESQL_DATABASE: city-db
          ports:
            - 5432:5432
          options: >-
            --health-cmd pg_isready
            --health-interval 10s
            --health-retries 5
      steps:
        - uses: actions/checkout@v3
        - uses: dtolnay/rust-toolchain@stable
        - uses: Swatinem/rust-cache@v2
        - name: Init sql script
          run: psql -h postgres -d city-db -U root -f ./sql/init.sql
          env:
            PGPASSWORD: root
        - name: Run tests
          run: cargo test
