name: Build Docker image

on:
  workflow_run:
    workflows: [CI]
    branches: [master]
    types:
      - completed

env:
  CARGO_TERM_COLOR: always
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-app:
    runs-on: ubuntu-22.04
    permissions:
      packages: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Add Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/lapsus-ord/city-api
          tags: latest

      - name: Login to github container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
