name: Build and release versioned Docker image

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

env:
  CARGO_TERM_COLOR: always
  SQLX_OFFLINE: true
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push to GHCR
        run: |
          docker build . --tag ghcr.io/lapsus-ord/city-api:${{ github.ref_name }} --target production
          docker push ghcr.io/lapsus-ord/city-api:${{ github.ref_name }}
